### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mstimberg** [eferrea/BCI-Master#3]
[Opened as part of JOSS review openjournals/joss-reviews#3956]

The README file is currently the only existing documentation, and is a bit sparse (even though maybe a lot of this is very conventional for BCI software). In particular:
 * The elements of the GUI could need more information: Why are the units presented in 4 panels (only for space reasons?) and what are the axes (x = channel and y = unit?). How exactly is the "tuning strength" encoded in the colors (a colorbar might be helpful as well)? What do the columns in the table show?
 * The "extended functionalities" also merit some more explanation. In particular, it is sometimes unclear in what order these functionalities can be used: there is a "Load Decoder" but no "Save Decoder" – are decoders saved automatically? At what point should one change "Shared Control", etc. Also, I did not immediately understand the difference between "Check correlation" and "BCIIDLE".
 * The Matlab code for `BCI_Loop` has some comments how to call it (e.g. with suggestions for the update time and the number of neurons), but other functions/classes like `simNeurons_2D_velocity` do not state what their arguments are; this information is only included in individual comments in the source code itself.
 * Finally, the `BCImat` folder contains some basic tests in the `Test` folder, but it is unclear what these do (and they also have hardcoded IP addresses).

**Comment by eferrea** [comment]
Hi @mstimberg, 
* In the figure legend I better explain, how users should interpret the GUI features and the reason why the units were separated in four matrixes. Unfortunately, when I tested the color bar it was slowing down the update of the online display. The value of the color can be still read from the R2 column.  
* An better explanation of the extended functionalities was added in the readme file.
* Other contents of the package like sumNeurons_2D_velocity were also better explained in a dedicated paragraph in the readme file.
* They are used for simple tests of VRPN connection and  the cbmex.m connection (application mode). I renamed the folder Test_connections for clarity. An explanation of the content of this folder is also provided in the readme now.  The code has also been cleaned and generic local host IP addresses used.

**Comment by mstimberg** [comment]
Great, that is indeed much clearer. I cannot judge all the details, but at least everything seems to be mentioned.
Minor nitpick: The README states: "...extensively explained in the *Matlab Graphical user interface extended functionalities* paragraph ..." but the paragraph heading is called "Matlab Graphical user interface functionalities" (i.e. without "extended")

**Comment by mstimberg** [comment]
One more very minor thing: it would be good to include the full reference for "Wu et al. 2006" in the README file (and not only in the paper) to make it self-contained.

**Comment by eferrea** [comment]
Thanks also for pointing this out. I removed from the figure legend the word "extended" since the description is about all functionalities. I also included the full reference at the end of the readme.
