### ISSUE TITLE
 Automatic tests or test procedures

### ISSUE THREAD

**Issue by mstimberg** [eferrea/BCI-Master#4]
[Opened as part of JOSS review openjournals/joss-reviews#3956]

Obviously, automatic testing GUI software is complicated, so I don't expect the authors to write a test suite covering the full functionality of their software. It would be nice, however, to have clearer instructions on what is expected when using the artificial neurons. Something along the lines of "perform about 50 reaches in the task controller, then select about 20 units with a tuning strength above X. After pressing "Switch BCI", the cursor movement should go to the points on a fairly straight line; "Check correlation" should show correlations around Y". When I tested the software, it seemed to do something reasonable, but I wasn't really sure what to expect in detail.

**Comment by eferrea** [comment]
Hi @mstimberg,
a dedicated  "test procedure (simulation mode)" paragraph was added to the readme file with a detailed explanation of what the user should do and what should expect during the first  session.

**Comment by mstimberg** [comment]
Thanks, this is much easier to follow now. In Point 4 of the test procedure you say:
> After collecting enough samples (samples are shown on the right table, 150-200 for good performance) press the Switch BCI button to start the decoder.

Could you maybe add that "collecting samples" here means to continue to perform the reaching task, and that the samples are only updated when you press "Update Regression" again? Of course, only if that is actually the case :)

**Comment by eferrea** [comment]
Thanks that is right. I now changed the text to be a bit more clear:
After collecting enough samples by continuously reaching the target and updating by pressing the Update Regression Button (samples are shown on the right table, 150-200 for good performance), press the Switch BCI button to start the decoder.
