### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by mstimberg** [eferrea/BCI-Master#6]
[Opened as part of JOSS review openjournals/joss-reviews#3956]
 
The repository should mention where users should contact you, whether you are interested in contribution and what system (e.g. GitHub issues and Pull Requests) you use for bug reports and contributions.

**Comment by eferrea** [comment]
Hi @mstimberg, thanks for pointing this out. A CONTRIBUTING.md file was added to the repository with instructions on how to contribute to this project.

**Comment by mstimberg** [comment]
Great, looks good to me.
